### ISSUE TITLE
Trying to add native arrays with methods into my own version.

### ISSUE THREAD

**Issue by JanEricNitschke** [HallofFamer/Lox2#1]
Hi, this is an awesome repo. I saw your reply in the issue regarding native classes (especially arrays) on the book repo and was now trying to add those to my own version that i am writing in rust (very very closely based on this repo https://github.com/abesto/clox-rs/) by looking how you did it.

But i am not quite able to put all the pieces together yet.

My first version was to just add a new `List` type directly to the values in the same way that the book handles numbers.

(Add a List(List) enum here with List just being a wrapper around a rust vector: https://github.com/abesto/clox-rs/blob/main/src/value.rs#L26).

Then i added the handling for creating then with the normal literal syntax and indexing into them. I also added native functions that expect a list as their first argument. (append(my_list, some_value)). (Like these existing ones: https://github.com/abesto/clox-rs/blob/main/src/native_functions.rs#L21).

However that is pretty clunky. To write. So i wanted to instead turn them into a native class with native methods that can be accessed with the `.` notation.

I have now managed to add an `Array` native class and also managed to attach the append function to it as a native method.

(It works exactly like native functions accept that i manipulate the stack such that the first argument is the receiving instance again).

However i am now having the issue that i can not connect these two parts:

- The List runtime value that has the backing rust vector (like Instance or Class are the actual rust/C objects)
- The Lox Array class that has the methods but is not connected to any actual dynamic array/vector.

Do i have to write an init method for the Array class that adds an `element` field to it that is then backed by the List(List) runtime type that i have?

Your project looks really awesome and i think there are a bunch of people who would eat it up (myself included) if you wrote a post/blog about all the stuff you have added and how it works from an implementation perspective.

Cheers

**Comment by HallofFamer** [comment]
Hi @JanEricNitschke, thank you for checking out my CLox repo and I am glad you like it. I do plan to write a blog series called 'Crafting Interpreters: The Lost Chapters' once I complete this entire project. It will take quite some time though, as I am experimenting features and implementations, I have a full time job as well. 

Regarding your question, yes it is necessary to write up an init method manually. This is what I've done with the Array class initializer: 

```
// Method declaration
LOX_METHOD(Array, init) {
    ASSERT_ARG_COUNT("Array::init()", 0);
    RETURN_OBJ(newArray(vm));
}

// function newArray
ObjArray* newArray(VM* vm) {
    ObjArray* array = ALLOCATE_OBJ(ObjArray, OBJ_ARRAY, vm->arrayClass);
    initValueArray(&array->elements);
    return array;
}
```

In my case it is a lot simpler since my array initializer creates an empty array(if you want to create an array with elements, you can do so with dedicated square bracket syntax such as [1, true, nil, "Hello World"]), if your array class accepts arguments you will need to do a bit more work to parse/validate the arguments, as well as write elements to the initial value array.

**Comment by JanEricNitschke** [comment]
Hi, thanks a lot.

I think I figured it out now and actually got a first working Implementation. Getting a list itself working as literals with the square syntax was fairly easy.

Getting things to work as a class with methods was tougher but I managed thanks to looking through your code.

The main thing was to also add a class attribute to my list implementation and then attaching the methods to that. After that I needed to adjust all the parts of the code that so far just expected an instance to also work with lists (for now could be expanded to include other native classes ).

My first idea of putting the lists into instances was more complicated and Introduced more indirection.

**Comment by HallofFamer** [comment]
All you need is to allow any Lox value to have methods, instead of just ObjInstance. It was actually a lot simpler to implement than I originally thought. Only issue is inheritance, that you may want to restrict inheritance for special classes such as String and List.
