### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by rubenanapu** [HallofFamer/Lox2#2]
Hi @HallofFamer,

I see that the code in https://github.com/munificent/craftinginterpreters has the MIT license.

But looking at this repository, https://github.com/HallofFamer/CLox, I see that it contains more things, like **try-catch**, "**_include_**" , and other great features.

I was thinking of forking this repository, rather than the **_craftinginterpreters_** repository basically to save time, and not have to reinvent the wheel. But when searching for the LICENSE file, I couldn't find it.

If I fork this repository, does it follow the MIT license? I don't understand those License-related things, but I just have a feeling that I need to ask you before forking.

I would be really grateful if you could add a LICENSE file to this repo to make this clearer.

Thanks in advance.

May God bless you.

**Comment by HallofFamer** [comment]
@rubenanapu I've just added an MIT license to this repo, and yes you can fork from it and make any customization as you want. With this being said, I do not recommend forking from the master branch, as I make daily updates which are incomplete and may not even be guaranteed to be working. Instead, I'd recommend using a release branch such as [v1.8.0](https://github.com/HallofFamer/CLox/tree/v1.8.0) or [v1.7.0](https://github.com/HallofFamer/CLox/tree/v1.7.0) as a starting point, unless you want to wait till the next release which may be months away.

**Comment by rubenanapu** [comment]
Hi @HallofFamer,

Thank you very much for adding the LICENSE file.

Thanks also for the recommendations about which branch to fork.

I wish you all the best.

Cheers.
