### ISSUE TITLE
Is there a plan to provide a JIT implementation for clox?

### ISSUE THREAD

**Issue by zxylllll** [HallofFamer/Lox2#4]
This seems interesting and challenging.

**Comment by HallofFamer** [comment]
Yeah I am definitely thinking about trying to implement a JIT compiler for CLox in future, as I do plan to introduce a profiler for CLox 2.4 or 2.5, which will be the prerequisite for a JIT that optimizes based on hot loops/functions. If this will happen, the JIT will most likely only be able to target x86-64 platform, as I am only familiar with WASM assembly. 

With this being said, I dont expect that it will not happen anytime soon. For CLox 2.0 till 2.3, the main focus is to enhance the type system, to add an optional type system, support generics and union types will take a substantial amount of time. On the other hand, I have my own idea how reified generics can be implemented in an OO language that supports metaclasses, but will experiment and see how it goes.
